name: rapid_rounds
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  # firebase_auth: ^5.4.0
  cloud_firestore: ^5.4.4
  flutter_timer_countdown: ^1.0.7
  flutter_bloc: ^7.0.0
  uuid: ^4.5.1
  rxdart: ^0.27.0
  flutter_dotenv: ^5.2.1
  lazy_load_indexed_stack: ^1.1.0
  mesh_gradient: ^1.3.8
  cached_network_image: ^3.4.1
  neopop: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/fonts/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Barr
      fonts:
        - asset: assets/fonts/Barriecito-Regular.ttf
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Custom
      fonts:
        - asset: assets/fonts/Custom.ttf
    - family: Avatars
      fonts:
        - asset: assets/fonts/Avatars.ttf
