/// Flutter icons Custom
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';
  static const String? _kFontPkg = null;

  static const IconData sort = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mon_5 = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leave = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_right = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic_wand = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_moustache = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_down = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_left = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_small_up = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
